1.导入 numpy 库

In [76]:
import numpy as np

2.建立一个一维数组 a，初始化为[4,5,6]

In [77]:
a=numpy.array([4,5,6])

(1)输出 a 的类型（type）

In [78]:
type(a)

numpy.ndarray

(2)输出 a 的各维度大小（shape）

In [79]:
a.shape

(3,)

(3)输出 a 的第一个元素

In [80]:
a[0]

4

3、建立一个二维数组 b，初始化为[[4,5,6],[1,2,3]]

In [81]:
b=np.array([[4,5,6],[1,2,3]])

(1) 输出 b 的各维度大小（shape）

In [82]:
b.shape

(2, 3)

(2) 输出b[0,0], b[0,1], b[1,1]这三个元素

In [83]:
b[0,0],b[0,1],b[1,1]

(4, 5, 2)

4、建立矩阵

(1) 建立一个大小为3 × 3的全 0 矩阵 c

In [84]:
c=np.zeros([3,3])

(2) 建立一个大小为4 × 5的全 1 矩阵 d

In [85]:
d=np.ones([4,5])

(3) 建立一个大小为4 × 4的单位矩阵 e

In [86]:
e = np.eye(4)

5、建立一个数组 f，初始化为[0,1,2,3,4,5,6,7,8,9,10,11]（arange）

In [87]:
f=np.arange(12)

(1) 输出 f 以及 f 的各维度大小

In [88]:
f,f.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

(2) 将 f 的 shape 改为3 × 4（reshape）

In [89]:
f=f.reshape([3,4])

(3) 输出 f 以及 f 的各维度大小

In [90]:
f,f.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

(4) 输出 f 第二行（f[1, ∶]）

In [91]:
f[1,:]

array([4, 5, 6, 7])

(5) 输出 f 最后两列（f[: ,2:]）

In [92]:
f[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

(6) 输出 f 第三行最后一个元素（使用-1 表示最后一个元素）

In [93]:
f[2,-1]

11